### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by mattbruton**
First attempt at html/css quiz. Elements shift around when browser size is anything but max width, but as long as that is true, everything shows up positioned correctly for me!

### CODE REVIEW

**Comment by zoeames** [comment]
Hey Matt,  looking great so far!  Just one thing holding you back from a thumbs up:
1.  looks like you set widths on your card to pixel values - please change those to percentages (i think it says 30% in the instructions)

**Comment by mattbruton** [comment]
corrected issue on article width.

**Comment by mattbruton** [comment]
Did I need to change something else on this one or am I good to merge?

**Comment by zoeames** [comment]
:+1:

**Pull request merged**
